- name: Setup Publishing
  run: |
    echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
    echo "@snupo:registry=https://registry.npmjs.org/" >> .npmrc
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

- name: Publish Package
  run: npm publish
  working-directory: ./packages/vite-plugin-jmx