name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Hardcore npm Auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > $HOME/.npmrc
          echo "@snupo:registry=https://registry.npmjs.org/" >> $HOME/.npmrc
          echo "Always-auth=true" >> $HOME/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Publish JMX
        working-directory: ./packages/jmx
        run: npm publish --access public --registry https://registry.npmjs.org/

      - name: Publish Plugin
        working-directory: ./packages/vite-plugin-jmx
        run: npm publish --access public --registry https://registry.njs.org/